apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  USERNAME: dXRzaGFi   # base64 for 'utshab'
  PASSWORD: cGFzc3dvcmQ=   # base64 for 'password'
  username.txt: dXRzaGFi   # base64 for 'utshab'
  release: cGFzc3dvcmQ=
  my.name: dXRzaGFi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          env:
          - name: TZ
            value: Asia/Singapore
          envFrom:
            - secretRef:
                name: my-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-mount
  template:
    metadata:
      labels:
        app: secret-mount
    spec:
      containers:
        - name: my-container
          image: nginx
          env:
            - name: MY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: release
            - name: my.name
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: my.name
            - name: ur.name
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: my.name
          volumeMounts:
            - name: my-secret-volume
              mountPath: /tmp/secret-data/mytext.txt
              subPath: username.txt
              readOnly: true

      volumes:
        - name: my-secret-volume
          secret:
            secretName: my-secret
  