apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    app: {{ include "app-chart.fullname" . }}
    environment: {{ .Values.env }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "app-chart.fullname" . }}
      environment: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ include "app-chart.fullname" . }}
        environment: {{ .Values.env }}
    spec:
      containers:
        - name: {{ include "app-chart.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.containerPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
