apiVersion: v1
kind: Service
metadata:
  name: {{ include "app-chart.fullname" . }}
  labels:
    app: {{ include "app-chart.fullname" . }}
    environment: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.servicePort }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    app: {{ include "app-chart.fullname" . }}
    environment: {{ .Values.env }}
