# Stage values override
env: dev
replicaCount: 1
image:
  repository: utssaha/streamlit-issue-poc
  tag: "v1"
  pullPolicy: Always
service:
  type: NodePort
  servicePort: 8501
  containerPort: 8501
resources: {}
